### ISSUE TITLE
error : npm install voiceplay

### ISSUE THREAD

**Issue by dony71** [tajddin/voiceplay#2]
node -v >>> v.6.7.0
npm -v >>> v.3.10.3

pi@RetrOrangePi:~$ sudo npm install voiceplay
npm WARN excluding symbolic link utils/ncov -> lib/ncov.js
npm WARN deprecated lodash-node@2.4.1: This package is discontinued. Use lodash@^4.0.0.
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated CSSselect@0.4.1: the module is now available as 'css-select'
npm WARN deprecated CSSwhat@0.4.7: the module is now available as 'css-what'
npm WARN excluding symbolic link utils/ncov -> lib/ncov.js

> mdns@2.2.8 install /home/pi/node_modules/mdns
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/6.7.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/home/pi/node_modules/mdns/.node-gyp"
make: Entering directory '/home/pi/node_modules/mdns/build'
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_sd.o
In file included from ../src/mdns.hpp:12:0,
                 from ../src/dns_sd.cpp:1:
../../nan/nan.h:261:25: error: redefinition of ‘template<class T> v8::Local<T> _NanEnsureLocal(v8::Local<T>)’
 NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Local<T> val) {
                         ^
../../nan/nan.h:256:25: note: ‘template<class T> v8::Local<T> _NanEnsureLocal(v8::Handle<T>)’ previously declared here
 NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Handle<T> val) {
                         ^
../../nan/nan.h:473:20: error: variable or field ‘NanAddGCEpilogueCallback’ declared void
       v8::Isolate::GCEpilogueCallback callback
                    ^
../../nan/nan.h:473:7: error: ‘GCEpilogueCallback’ is not a member of ‘v8::Isolate’
       v8::Isolate::GCEpilogueCallback callback
       ^
../../nan/nan.h:474:18: error: expected primary-expression before ‘gc_type_filter’
     , v8::GCType gc_type_filter = v8::kGCTypeAll) {
                  ^
../../nan/nan.h:479:20: error: variable or field ‘NanRemoveGCEpilogueCallback’ declared void
       v8::Isolate::GCEpilogueCallback callback) {
                    ^
../../nan/nan.h:479:7: error: ‘GCEpilogueCallback’ is not a member of ‘v8::Isolate’
       v8::Isolate::GCEpilogueCallback callback) {
       ^
../../nan/nan.h:484:20: error: variable or field ‘NanAddGCPrologueCallback’ declared void
       v8::Isolate::GCPrologueCallback callback
                    ^
../../nan/nan.h:484:7: error: ‘GCPrologueCallback’ is not a member of ‘v8::Isolate’
       v8::Isolate::GCPrologueCallback callback
       ^
../../nan/nan.h:485:18: error: expected primary-expression before ‘gc_type_filter’
     , v8::GCType gc_type_filter = v8::kGCTypeAll) {
                  ^
../../nan/nan.h:490:20: error: variable or field ‘NanRemoveGCPrologueCallback’ declared void
       v8::Isolate::GCPrologueCallback callback) {
                    ^
../../nan/nan.h:490:7: error: ‘GCPrologueCallback’ is not a member of ‘v8::Isolate’
       v8::Isolate::GCPrologueCallback callback) {
       ^
../../nan/nan.h:661:13: error: ‘node::smalloc’ has not been declared
     , node::smalloc::FreeCallback callback
             ^
../../nan/nan.h:661:35: error: expected ‘,’ or ‘...’ before ‘callback’
     , node::smalloc::FreeCallback callback
                                   ^
../../nan/nan.h: In function ‘v8::Localv8::Object NanNewBufferHandle(char_, size_t, int)’:
../../nan/nan.h:665:50: error: ‘callback’ was not declared in this scope
         v8::Isolate::GetCurrent(), data, length, callback, hint);
                                                  ^
../../nan/nan.h:665:60: error: ‘hint’ was not declared in this scope
         v8::Isolate::GetCurrent(), data, length, callback, hint);
                                                            ^
../../nan/nan.h: In function ‘v8::Localv8::Object NanNewBufferHandle(const char_, uint32_t)’:
../../nan/nan.h:672:67: error: invalid conversion from ‘const char_’ to ‘char_’ [-fpermissive]
     return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
                                                                   ^
In file included from ../../nan/nan.h:25:0,
                 from ../src/mdns.hpp:12,
                 from ../src/dns_sd.cpp:1:
/home/pi/node_modules/mdns/.node-gyp/6.7.0/include/node/node_buffer.h:46:40: note: initializing argument 2 of ‘v8::MaybeLocalv8::Object node::Buffer::New(v8::Isolate_, char_, size_t)’
 NODE_EXTERN v8::MaybeLocalv8::Object New(v8::Isolate\* isolate,
                                        ^
In file included from ../src/mdns.hpp:12:0,
                 from ../src/dns_sd.cpp:1:
../../nan/nan.h:672:67: error: could not convert ‘node::Buffer::New(v8::Isolate::GetCurrent(), ((char_)data), size)’ from ‘v8::MaybeLocalv8::Object’ to ‘v8::Localv8::Object’
     return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
                                                                   ^
../../nan/nan.h: In function ‘v8::Localv8::Object NanNewBufferHandle(uint32_t)’:
../../nan/nan.h:676:61: error: could not convert ‘node::Buffer::New(v8::Isolate::GetCurrent(), size)’ from ‘v8::MaybeLocalv8::Object’ to ‘v8::Localv8::Object’
     return node::Buffer::New(v8::Isolate::GetCurrent(), size);
                                                             ^
../../nan/nan.h: In function ‘v8::Localv8::Object NanBufferUse(char_, uint32_t)’:
../../nan/nan.h:683:12: error: ‘Use’ is not a member of ‘node::Buffer’
     return node::Buffer::Use(v8::Isolate::GetCurrent(), data, size);
            ^
dns_sd_bindings.target.mk:139: recipe for target 'Release/obj.target/dns_sd_bindings/src/dns_sd.o' failed
make: **\* [Release/obj.target/dns_sd_bindings/src/dns_sd.o] Error 1
make: Leaving directory '/home/pi/node_modules/mdns/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 3.4.112-sun8i
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/pi/node_modules/mdns
gyp ERR! node -v v6.7.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
/home/pi
├─┬ express@4.14.0
│ ├─┬ accepts@1.3.3
│ │ ├─┬ mime-types@2.1.12
│ │ │ └── mime-db@1.24.0
│ │ └── negotiator@0.6.1
│ ├── array-flatten@1.1.1
│ ├── content-disposition@0.5.1
│ ├── content-type@1.0.2
│ ├── cookie@0.3.1
│ ├── cookie-signature@1.0.6
│ ├─┬ debug@2.2.0
│ │ └── ms@0.7.1
│ ├── depd@1.1.0
│ ├── encodeurl@1.0.1
│ ├── escape-html@1.0.3
│ ├── etag@1.7.0
│ ├─┬ finalhandler@0.5.0
│ │ ├── statuses@1.3.0
│ │ └── unpipe@1.0.0
│ ├── fresh@0.3.0
│ ├── merge-descriptors@1.0.1
│ ├── methods@1.1.2
│ ├─┬ on-finished@2.3.0
│ │ └── ee-first@1.1.1
│ ├── parseurl@1.3.1
│ ├── path-to-regexp@0.1.7
│ ├─┬ proxy-addr@1.1.2
│ │ ├── forwarded@0.1.0
│ │ └── ipaddr.js@1.1.1
│ ├── qs@6.2.0
│ ├── range-parser@1.2.0
│ ├─┬ send@0.14.1
│ │ ├── destroy@1.0.4
│ │ ├─┬ http-errors@1.5.0
│ │ │ ├── inherits@2.0.1
│ │ │ └── setprototypeof@1.0.1
│ │ └── mime@1.3.4
│ ├── serve-static@1.11.1
│ ├─┬ type-is@1.6.13
│ │ └── media-typer@0.3.0
│ ├── utils-merge@1.0.0
│ └── vary@1.1.0
├─┬ natural@0.2.1
│ ├── apparatus@0.0.9
│ ├── sylvester@0.0.21
│ └── underscore@1.8.3
├── nlp_compromise@1.1.5
├─┬ opennlp@1.1.0
│ ├── extendy@1.0.1
│ └─┬ java@0.4.7
│   ├─┬ find-java-home@0.1.2
│   │ └── which@1.0.9
│   ├─┬ glob@3.2.11
│   │ └─┬ minimatch@0.3.0
│   │   ├── lru-cache@2.7.3
│   │   └── sigmund@1.0.1
│   └── nan@1.4.1
├─┬ youtube-node@1.3.0
│ ├── colors@1.0.3
│ ├─┬ prompt@0.2.14
│ │ ├── pkginfo@0.4.0
│ │ ├─┬ read@1.0.7
│ │ │ └── mute-stream@0.0.6
│ │ ├── revalidator@0.1.8
│ │ ├─┬ utile@0.2.1
│ │ │ ├── async@0.2.10
│ │ │ ├── deep-equal@1.0.1
│ │ │ ├── i@0.3.5
│ │ │ ├─┬ mkdirp@0.5.1
│ │ │ │ └── minimist@0.0.8
│ │ │ ├── ncp@0.4.2
│ │ │ └─┬ rimraf@2.5.4
│ │ │   └─┬ glob@7.1.0
│ │ │     ├── fs.realpath@1.0.0
│ │ │     ├─┬ inflight@1.0.5
│ │ │     │ └── wrappy@1.0.2
│ │ │     ├─┬ minimatch@3.0.3
│ │ │     │ └─┬ brace-expansion@1.1.6
│ │ │     │   ├── balanced-match@0.4.2
│ │ │     │   └── concat-map@0.0.1
│ │ │     ├── once@1.4.0
│ │ │     └── path-is-absolute@1.0.1
│ │ └─┬ winston@0.8.3
│ │   ├── colors@0.6.2
│ │   ├── cycle@1.0.3
│ │   ├── eyes@0.1.8
│ │   ├── pkginfo@0.3.1
│ │   └── stack-trace@0.0.9
│ └─┬ request@2.53.0
│   ├── aws-sign2@0.5.0
│   ├─┬ bl@0.9.5
│   │ └─┬ readable-stream@1.0.34
│   │   ├── core-util-is@1.0.2
│   │   ├── isarray@0.0.1
│   │   └── string_decoder@0.10.31
│   ├── caseless@0.9.0
│   ├─┬ combined-stream@0.0.7
│   │ └── delayed-stream@0.0.5
│   ├── forever-agent@0.5.2
│   ├─┬ form-data@0.2.0
│   │ ├── async@0.9.2
│   │ └─┬ mime-types@2.0.14
│   │   └── mime-db@1.12.0
│   ├─┬ hawk@2.3.1
│   │ ├── boom@2.10.1
│   │ ├── cryptiles@2.0.5
│   │ ├── hoek@2.16.3
│   │ └── sntp@1.0.9
│   ├─┬ http-signature@0.10.1
│   │ ├── asn1@0.1.11
│   │ ├── assert-plus@0.1.5
│   │ └── ctype@0.5.3
│   ├── isstream@0.1.2
│   ├── json-stringify-safe@5.0.1
│   ├─┬ mime-types@2.0.14
│   │ └── mime-db@1.12.0
│   ├── node-uuid@1.4.7
│   ├── oauth-sign@0.6.0
│   ├── qs@2.3.3
│   ├── stringstream@0.0.5
│   ├── tough-cookie@2.3.1
│   └── tunnel-agent@0.4.3
└─┬ ytdl-core@0.5.1
  ├─┬ cheerio@0.18.0
  │ ├─┬ CSSselect@0.4.1
  │ │ ├── CSSwhat@0.4.7
  │ │ └── domutils@1.4.3
  │ ├─┬ dom-serializer@0.0.1
  │ │ └── domelementtype@1.1.3
  │ ├── entities@1.1.1
  │ ├─┬ htmlparser2@3.8.3
  │ │ ├── domelementtype@1.3.0
  │ │ ├── domhandler@2.3.0
  │ │ ├── domutils@1.5.1
  │ │ ├── entities@1.0.0
  │ │ └── readable-stream@1.1.14
  │ └── lodash@2.4.2
  └─┬ jstream@0.2.10
    └── clarinet@0.11.0

npm WARN enoent ENOENT: no such file or directory, open '/home/pi/package.json'
npm WARN pi No description
npm WARN pi No repository field.
npm WARN pi No README data
npm WARN pi No license field.
npm ERR! Linux 3.4.112-sun8i
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "voiceplay"
npm ERR! node v6.7.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE

npm ERR! mdns@2.2.8 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mdns@2.2.8 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the mdns package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs mdns
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls mdns
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/npm-debug.log

**Comment by sticilface** [comment]
I get this installing on FreeBSD 9.3 and on ubuntu 16 and on my mac

**Comment by BartschLabs** [comment]
Try downgrading your version of node.js.
