### ISSUE TITLE
Build fails at node-gyp rebuild on macOS

### ISSUE THREAD

**Issue by dariokan82** [tajddin/voiceplay#7]
info lifecycle mdns@2.2.8~install: mdns@2.2.8
868 verbose lifecycle mdns@2.2.8~install: unsafe-perm in lifecycle false
869 verbose lifecycle mdns@2.2.8~install: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/dario/node_modules/mdns/node_modules/.bin:/Users/dario/node_modules/.bin:/usr/local/Cellar/node/7.3.0/bin:/Library/Frameworks/Python.framework/Versions/3.5/bin:/Library/Frameworks/Python.framework/Versions/3.5/bin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/git/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/dario/.rvm/bin
870 verbose lifecycle mdns@2.2.8~install: CWD: /Users/dario/node_modules/mdns
871 silly lifecycle mdns@2.2.8~install: Args: [ '-c', 'node-gyp rebuild' ]
872 silly lifecycle mdns@2.2.8~install: Returned: code: 1  signal: null
873 info lifecycle mdns@2.2.8~install: Failed to exec install script
874 verbose unlock done using /Users/dario/.npm/_locks/staging-18a915515c4fa0b4.lock for /Users/dario/node_modules/.staging
875 silly rollbackFailedOptional Starting
876 silly rollbackFailedOptional Finishing
877 silly runTopLevelLifecycles Finishing
878 silly install printInstalled
879 warn enoent ENOENT: no such file or directory, open '/Users/dario/package.json'
880 verbose enoent ENOENT: no such file or directory, open '/Users/dario/package.json'
880 verbose enoent This is most likely not a problem with npm itself
880 verbose enoent and is related to npm not being able to find a file.
881 warn dario No description
882 verbose If you need help, you may report this error at:
882 verbose     <https://github.com/npm/npm/issues>
883 warn dario No repository field.
884 verbose If you need help, you may report this error at:
884 verbose     <https://github.com/npm/npm/issues>
885 warn dario No README data
886 verbose If you need help, you may report this error at:
886 verbose     <https://github.com/npm/npm/issues>
887 warn dario No license field.
888 verbose If you need help, you may report this error at:
888 verbose     <https://github.com/npm/npm/issues>
889 verbose stack Error: mdns@2.2.8 install: `node-gyp rebuild`
889 verbose stack Exit status 1
889 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
889 verbose stack     at emitTwo (events.js:106:13)
889 verbose stack     at EventEmitter.emit (events.js:191:7)
889 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
889 verbose stack     at emitTwo (events.js:106:13)
889 verbose stack     at ChildProcess.emit (events.js:191:7)
889 verbose stack     at maybeClose (internal/child_process.js:885:16)
889 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
890 verbose pkgid mdns@2.2.8
891 verbose cwd /Users/dario
892 error Darwin 16.3.0
893 error argv "/usr/local/Cellar/node/7.3.0/bin/node" "/usr/local/bin/npm" "install" "voiceplay"
894 error node v7.3.0
895 error npm  v3.10.10
896 error code ELIFECYCLE
897 error mdns@2.2.8 install: `node-gyp rebuild`
897 error Exit status 1
898 error Failed at the mdns@2.2.8 install script 'node-gyp rebuild'.
898 error Make sure you have the latest version of node.js and npm installed.
898 error If you do, this is most likely a problem with the mdns package,
898 error not with npm itself.
898 error Tell the author that this fails on your system:
898 error     node-gyp rebuild
898 error You can get information on how to open an issue for this project with:
898 error     npm bugs mdns
898 error Or if that isn't available, you can get their info via:
898 error     npm owner ls mdns
898 error There is likely additional logging output above.
899 verbose exit [ 1, true ]

**Comment by tim-mc** [comment]
@dariokan82 Same error here, I switched over to node 6.9.1 / npm 4.0.3 (via nvm) and the package installed successfully.

**Comment by dariokan82** [comment]
Tried downgrading to 6.9.1/4.0.3, build still fails at node-gyp. 

I also tried downgrading to 5.7.1 to downgrade node-gyp, with no luck.

I modified the dependencies in the .json packages to use the up-to-date mdns package and by doing so I managed to get the sever up and running, which would respond to the Youtube command but crash before initiating AirPlay, so I'm stuck to one.

**Comment by BartschLabs** [comment]
I had to downgrade to node 4.x to get it to install.  Got the server up and running but I don't get "Airplay device discovered: Apple TV.  Ready to start receiving requests from the AWS Lambda function."

**Comment by grobbie** [comment]
```
brew install npm
brew install ffmpeg

curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.1/install.sh | bash

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

nvm install v4
git clone https://github.com/guerrerocarlos/node-airplay-js.git
cd node-airplay-js && npm install

cd ..
git clone https://github.com/tajddin/voiceplay.git
cd voiceplay
vi package.json

# edit this line:
# "airplay2": "git+https://github.com/tajddin/node-airplay.git",
# replace with:
# "airplay-js": "../node-airplay-js",

# edit this line:
# "opennlp": "^1.1.0",
# replace with:
# "opennlp": "^2.0.0",

# edit this line:
# "ytdl-core": "0.5.1",
# replace with:
# "ytdl-core": "^0.13.1",

npm install

vi airplay.js
# edit this line:
# var browser = require('airplay2').createBrowser();
# replace with:
# var browser = require('airplay-js').createBrowser();

node voiceplay
```
